"""add pipeline_version

Revision ID: 4cf12e9911d7
Revises: 9b22eb56d106
Create Date: 2026-08-14 19:52:20.898332

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel 类型（AutoString 等）在自动生成迁移中使用
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4cf12e9911d7'
down_revision: str | Sequence[str] | None = '9b22eb56d106'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('failed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestjob_doc_id'), 'ingestjob', ['doc_id'], unique=False)
    op.create_index(op.f('ix_ingestjob_kb_id'), 'ingestjob', ['kb_id'], unique=False)
    op.create_index(op.f('ix_ingestjob_stage'), 'ingestjob', ['stage'], unique=False)
    op.add_column(
        "document",
        sa.Column("pipeline_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'pipeline_version')
    op.drop_index(op.f('ix_ingestjob_stage'), table_name='ingestjob')
    op.drop_index(op.f('ix_ingestjob_kb_id'), table_name='ingestjob')
    op.drop_index(op.f('ix_ingestjob_doc_id'), table_name='ingestjob')
    op.drop_table('ingestjob')
    # ### end Alembic commands ###
