"""baseline

Revision ID: 9b22eb56d106
Revises: 
Create Date: 2026-08-14 17:50:43.552781

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel 类型（AutoString 等）在自动生成迁移中使用
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b22eb56d106'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunkrow',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunkrow_doc_id'), 'chunkrow', ['doc_id'], unique=False)
    op.create_index(op.f('ix_chunkrow_kb_id'), 'chunkrow', ['kb_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_kb_id'), 'document', ['kb_id'], unique=False)
    op.create_table('knowledgebase',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledgebase')
    op.drop_index(op.f('ix_document_kb_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_chunkrow_kb_id'), table_name='chunkrow')
    op.drop_index(op.f('ix_chunkrow_doc_id'), table_name='chunkrow')
    op.drop_table('chunkrow')
    # ### end Alembic commands ###
